language: csharp
solution: SuccincT.sln
env:
  - EnableNuGetPackageRestore=true
install:
  - nuget restore SuccincT.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release SuccincT.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./SuccincTTests/bin/Release/SuccincTTests.dll